version: '3.8'

services:
  app:
    build:
      dockerfile: docker/backend/Dockerfile
    container_name: laravel_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
      - ./backend/vendor:/var/www/vendor
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb_vue
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  frontend:
    build:
      dockerfile: docker/frontend/Dockerfile
    container_name: vue_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    networks:
      - app_network
    depends_on:
      - app

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www
    depends_on:
      - app
      - frontend
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data: